### ISSUE TITLE
reference_marker

### ISSUE THREAD

**Issue by Tommaso12** [saeyslab/FlowSOM_protocol#1]
Hi, I was wondering if you can five a bit more explanation about the `reference_marker`. In the protocol you choose PE. Is this because the color is associated to a particular marker? Thanks a lot!

**Comment by KatrienQ** [comment]
Hi,
I'm so sorry for responding so late, I did not notice an issue was raised. 
The `reference_marker` is used to determine the parameters to scale the scatters linearly. We picked PE, not specifically because it was associated with a certain marker, but because the marker expression there covered the whole range (i.e. negative and positive cells). If you would pick for example a marker with only low expression values, the scatter channel will be transformed to this lower range and will not contribute a lot to the SOM clustering.
I hope this helps!

**Comment by Tommaso12** [comment]
Hey! No worries! Thanks for the reply! Ok if I understood what you mean, I should then check which color has that best range (covering positive and negative values) of values so that the SSC-A and the FSC-A are meaningfully representing the whole events in my samples.

**Comment by KatrienQ** [comment]
Yes indeed, then the importance of the scatters in the clustering step will be in line with the other markers.
